import type { Metadata } from "next";
import { Lato, Poppins } from 'next/font/google';
import "./globals.css";

const lato = Lato({
  weight: ['400', '700'], 
  subsets: ['latin'],
});

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app dfadfad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${lato.className} ${poppins.className}`}
      >
        {children}
      </body>
    </html>
  );
}
